### ISSUE TITLE
Crash when users tried to move a screenshot to a collection (Nexus 5)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#151]
1. Launch Scryer
2. Long tap a screenshot
3. Tap Move to
4. Tap a collection

Reproduce rate: 10/10
https://drive.google.com/open?id=1_WYI4ms51D8Td5s0VmT7Iy4TykXOTaeY

Nexus 5
Android 6.0.1
Scryer Nightly 1.0 (294).nightly
 
--------- beginning of crash
09-13 10:46:46.036 10817 10817 E AndroidRuntime: FATAL EXCEPTION: main
09-13 10:46:46.036 10817 10817 E AndroidRuntime: Process: gro.allizom.scryer, PID: 10817
09-13 10:46:46.036 10817 10817 E AndroidRuntime: java.lang.NoSuchMethodError: No static method hashCode(J)I in class Ljava/lang/Long; or its super classes (declaration of 'java.lang.Long' appears in /system/framework/core-libart.jar)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at org.mozilla.scryer.persistence.CollectionModel.hashCode(CollectionModel.kt)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at java.util.Collections.secondaryHash(Collections.java:3427)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at java.util.HashMap.put(HashMap.java:385)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at org.mozilla.scryer.sortingpanel.SortingPanelActivity$onCollectionClicked$1.doResume(SortingPanelActivity.kt:320)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:14)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-13 10:46:46.036 10817 10817 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-13 10:46:46.050   779  1310 W ActivityManager:   Force finishing activity gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity
09-13 10:46:46.570   779   793 W ActivityManager: Activity pause timeout for ActivityRecord{ed6e7f7 u0 gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity t87 f}
09-13 10:46:47.918   779  1525 I WindowState: WIN DEATH: Window{45b2c01 u0 gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity}
09-13 10:46:47.921   779  1548 I WindowState: WIN DEATH: Window{1ad4afc u0 gro.allizom.scryer/org.mozilla.scryer.MainActivity}
09-13 10:46:47.956   779  2593 I ActivityManager: Process gro.allizom.scryer (pid 10817) has died
09-13 10:46:47.956   779  2593 D ActivityManager: cleanUpApplicationRecord -- 10817
09-13 10:46:47.960   779  2593 W ActivityManager: Scheduling restart of crashed service gro.allizom.scryer/org.mozilla.scryer.ScryerService in 1000ms
09-13 10:46:47.975   779  2593 I ActivityManager: Start proc 12144:gro.allizom.scryer/u0a86 for activity gro.allizom.scryer/org.mozilla.scryer.MainActivity
09-13 10:46:48.078   779   801 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-13 10:46:48.531   779  2598 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 10817 uid 10086
09-13 10:46:48.722   779   801 W WindowAnimator: Failed to dispatch window animation state change.
09-13 10:46:48.722   779   801 W WindowAnimator: android.os.DeadObjectException
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-13 10:46:48.722   779   801 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-13 10:46:54.258   779  1310 I ActivityManager: START u0 {cmp=gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity (has extras)} from uid 10086 on display 0
09-13 10:46:56.662 12144 12144 E AndroidRuntime: FATAL EXCEPTION: main
09-13 10:46:56.662 12144 12144 E AndroidRuntime: Process: gro.allizom.scryer, PID: 12144
09-13 10:46:56.662 12144 12144 E AndroidRuntime: java.lang.NoSuchMethodError: No static method hashCode(J)I in class Ljava/lang/Long; or its super classes (declaration of 'java.lang.Long' appears in /system/framework/core-libart.jar)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at org.mozilla.scryer.persistence.CollectionModel.hashCode(CollectionModel.kt)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at java.util.Collections.secondaryHash(Collections.java:3427)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at java.util.HashMap.put(HashMap.java:385)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at org.mozilla.scryer.sortingpanel.SortingPanelActivity$onCollectionClicked$1.doResume(SortingPanelActivity.kt:320)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:14)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-13 10:46:56.662 12144 12144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-13 10:46:56.664   779  1546 W ActivityManager:   Force finishing activity gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity
09-13 10:46:57.197   779   793 W ActivityManager: Activity pause timeout for ActivityRecord{8e4dcbb u0 gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity t88 f}
09-13 10:47:03.432   779  1546 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.AppCrashProxy (has extras)} from uid 1000 on display 0
09-13 10:47:03.473   779   789 I WindowState: WIN DEATH: Window{57c2a8 u0 gro.allizom.scryer/org.mozilla.scryer.MainActivity}
09-13 10:47:03.476   779  1310 I WindowState: WIN DEATH: Window{b778b25 u0 gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity}
09-13 10:47:03.506   779  2593 I ActivityManager: Process gro.allizom.scryer (pid 12144) has died
09-13 10:47:03.506   779  2593 D ActivityManager: cleanUpApplicationRecord -- 12144
09-13 10:47:03.517   779  2593 I ActivityManager: Start proc 12271:gro.allizom.scryer/u0a86 for activity gro.allizom.scryer/org.mozilla.scryer.MainActivity
09-13 10:47:03.537   779   790 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms cmp=com.google.android.gms/.feedback.FeedbackActivity (has extras)} from uid 10015 on display 0
09-13 10:47:03.587   779  1545 I ActivityManager: Start proc 12283:com.google.android.gms.ui/u0a7 for activity com.google.android.gms/.feedback.FeedbackActivity
09-13 10:47:03.589   779  1545 I ActivityManager: Killing 9651:com.google.android.instantapps.supervisor/u0a85 (adj 15): empty #17
09-13 10:47:03.618   779   801 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-13 10:47:03.630   779  1310 D ActivityManager: cleanUpApplicationRecord -- 9651
09-13 10:47:04.520   779  1875 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 12144 uid 10086
09-13 10:47:07.856   779   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 104]
09-13 10:47:09.996   779  1492 I ActivityManager: Start proc 12370:com.google.android.gms.feedback/u0a7 for service com.google.android.gms/.feedback.FeedbackAsyncService
09-13 10:47:10.565   779  1071 W InputMethodManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@c70c7d0 (uid=10007 pid=12283)
09-13 10:47:10.873   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 56
09-13 10:47:13.887   779   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 104]
09-13 10:47:13.893   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 60
09-13 10:47:16.909   779   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 104]
09-13 10:47:17.415   779  1875 I ActivityManager: Killing 10563:com.google.process.gapps/u0a42 (adj 15): empty #17
09-13 10:47:17.442   779  2597 D ActivityManager: cleanUpApplicationRecord -- 10563
09-13 10:47:17.877   779  2598 I ActivityManager: START u0 {cmp=gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity (has extras)} from uid 10086 on display 0
09-13 10:47:21.698   779  2597 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=gro.allizom.scryer/org.mozilla.scryer.MainActivity bnds=[12,573][276,870] (has extras)} from uid 10021 on display 0
09-13 10:47:21.707   779   793 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.googlequicksearchbox (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.reflection.ReflectionReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10021)
09-13 10:47:21.708   779   793 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.gms (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10021)
09-13 10:47:24.818   779  1546 I ActivityManager: START u0 {cmp=gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity (has extras)} from uid 10086 on display 0
09-13 10:47:27.175 12271 12271 E AndroidRuntime: FATAL EXCEPTION: main
09-13 10:47:27.175 12271 12271 E AndroidRuntime: Process: gro.allizom.scryer, PID: 12271
09-13 10:47:27.175 12271 12271 E AndroidRuntime: java.lang.NoSuchMethodError: No static method hashCode(J)I in class Ljava/lang/Long; or its super classes (declaration of 'java.lang.Long' appears in /system/framework/core-libart.jar)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at org.mozilla.scryer.persistence.CollectionModel.hashCode(CollectionModel.kt)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at java.util.Collections.secondaryHash(Collections.java:3427)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at java.util.HashMap.put(HashMap.java:385)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at org.mozilla.scryer.sortingpanel.SortingPanelActivity$onCollectionClicked$1.doResume(SortingPanelActivity.kt:320)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:14)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-13 10:47:27.175 12271 12271 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-13 10:47:27.177   779  1492 W ActivityManager:   Force finishing activity gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity
09-13 10:47:27.699   779   793 W ActivityManager: Activity pause timeout for ActivityRecord{ca558fe u0 gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity t93 f}
09-13 10:47:33.779   779   789 I WindowState: WIN DEATH: Window{dfa1b13 u0 gro.allizom.scryer/org.mozilla.scryer.MainActivity}
09-13 10:47:33.781   779  1875 I WindowState: WIN DEATH: Window{256374f u0 gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity}
09-13 10:47:33.826   779  1548 I ActivityManager: Process gro.allizom.scryer (pid 12271) has died
09-13 10:47:33.826   779  1548 D ActivityManager: cleanUpApplicationRecord -- 12271
09-13 10:47:33.828   779  1548 W ActivityManager: Scheduling restart of crashed service gro.allizom.scryer/org.mozilla.scryer.ScryerService in 1000ms
09-13 10:47:33.828   779  1548 W ActivityManager: Scheduling restart of crashed service gro.allizom.scryer/org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService in 11000ms
09-13 10:47:33.837   779  1548 I ActivityManager: Start proc 12640:gro.allizom.scryer/u0a86 for activity gro.allizom.scryer/org.mozilla.scryer.MainActivity
09-13 10:47:33.949   779   801 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-13 10:47:34.331   779  1548 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 12271 uid 10086
09-13 10:47:36.730   779  1546 I ActivityManager: START u0 {cmp=gro.allizom.scryer/org.mozilla.scryer.setting.SettingsActivity} from uid 10086 on display 0
09-13 10:47:42.222   779   874 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (has extras)} from uid 1000 on display 0
09-13 10:47:44.079   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 56
09-13 10:47:51.598   779   789 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.vending/.AssetBrowserActivity (has extras)} from uid 10021 on display 0
09-13 10:47:51.602   779   793 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.googlequicksearchbox (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.reflection.ReflectionReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10021)
09-13 10:47:51.605   779   793 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.gms (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10021)
09-13 10:48:02.231   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 60
09-13 10:48:03.155   779   874 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (has extras)} from uid 1000 on display 0
09-13 10:48:05.251   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 56
09-13 10:48:05.442   779  1525 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=gro.allizom.scryer/org.mozilla.scryer.MainActivity bnds=[12,573][276,870] (has extras)} from uid 10021 on display 0
09-13 10:48:05.450   779   793 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.googlequicksearchbox (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.reflection.ReflectionReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10021)
09-13 10:48:05.456   779   793 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.gms (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10021)
09-13 10:48:06.053   779   793 W ProcessCpuTracker: Skipping unknown process pid 12871
09-13 10:48:06.053   779   793 W ProcessCpuTracker: Skipping unknown process pid 12872
09-13 10:48:06.054   779   793 W ProcessCpuTracker: Skipping unknown process pid 12874
09-13 10:48:06.054   779   793 W ProcessCpuTracker: Skipping unknown process pid 12876
09-13 10:48:06.055   779   793 W ProcessCpuTracker: Skipping unknown process pid 12877
09-13 10:48:06.055   779   793 W ProcessCpuTracker: Skipping unknown process pid 12879
09-13 10:48:06.055   779   793 W ProcessCpuTracker: Skipping unknown process pid 12880
09-13 10:48:06.056   779   793 W ProcessCpuTracker: Skipping unknown process pid 12881
09-13 10:48:06.056   779   793 W ProcessCpuTracker: Skipping unknown process pid 12882
09-13 10:48:06.056   779   793 W ProcessCpuTracker: Skipping unknown process pid 12885
09-13 10:48:06.209   779  1548 I ActivityManager: START u0 {cmp=gro.allizom.scryer/org.mozilla.scryer.detailpage.DetailPageActivity (has extras)} from uid 10086 on display 0
09-13 10:48:08.259   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 60
09-13 10:48:12.430   779  1492 I ActivityManager: START u0 {cmp=gro.allizom.scryer/org.mozilla.scryer.sortingpanel.SortingPanelActivity (has extras)} from uid 10086 on display 0
09-13 10:48:16.856   779  1548 I ActivityManager: START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from uid 10086 on display 0
09-13 10:48:17.295   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 56
09-13 10:48:18.051   779  1310 I ActivityManager: START u0 {act=android.intent.action.SEND typ=image/* flg=0x1b080001 cmp=com.google.android.gm/.ComposeActivityGmailExternal clip={image/* U:file:///storage/emulated/0/Pictures/Screenshots/Screenshot_20180606-163138.png} (has extras)} from uid 10086 on display 0
09-13 10:48:18.333   779  1323 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.333   779  2593 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.334   779  2598 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.334   779   940 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.340   779   789 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.340   779  1492 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.341   779  1525 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.341   779  1310 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.705   779  1546 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:18.770   779  2597 D WifiService: acquireWifiLockLocked: WifiLock{MetadataSyncChimeraServ type=1 binder=android.os.BinderProxy@912da9c}
09-13 10:48:19.296   779  1525 D WifiService: releaseWifiLockLocked: WifiLock{MetadataSyncChimeraServ type=1 binder=android.os.BinderProxy@912da9c}
09-13 10:48:20.305   779   885 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 104] to 60
09-13 10:48:25.208   779   794 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc en_US ldltr sw360dp w592dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h s.11}
09-13 10:48:25.428   779  1548 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.428   779  1492 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.429   779  2593 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.429   779  1525 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.470   779  1071 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.471   779   790 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.471   779   789 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.472   779  1545 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.571   779   940 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.572   779   789 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.572   779  1548 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.573   779  1545 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007
09-13 10:48:25.672   779  2593 W AppOps  : Bad call: specified package com.google.android.gms under uid 10063 but it is really 10007

**Comment by weslyhuang** [comment]
basic function, P0.

**Comment by weslyhuang** [comment]
wait, not reproducible with my S8+, Android 8.0.0, with nightly build 294. is this device specific? @cynthiatang may need to check further.

**Comment by cynthiatang** [comment]
yes, it's Nexus 5 only

**Comment by weslyhuang** [comment]
thanks, i updated the title to emphasize it.

**Comment by cynthiatang** [comment]
Verified: fixed

Pixel2
Lenovo A1000m 
Android 5.1
ScreenshotGo 1.0(346).nightly
