### ISSUE TITLE
Crash when users launch Scryer (Galaxy J7 Prime)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#85]
1. Launch Scryer

Reproduce Rate: 10/10

Scryer 1.0(180).debug
Galaxy J7 Prime
Android 7.0

Video: https://drive.google.com/open?id=1KoAStk_OlpPrl6GysD4awxxFW9PY5WVk
Crash log:
--------- beginning of crash
```
09-05 10:43:14.342 24026 24175 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
09-05 10:43:14.342 24026 24175 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 24026
09-05 10:43:14.342 24026 24175 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-05 10:43:14.342 24026 24175 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-05 10:43:14.342 24026 24175 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-05 10:43:14.342 24026 24175 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-05 10:43:14.342 24026 24175 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-05 10:43:14.342 24026 24175 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-05 10:43:14.342 24026 24175 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-05 10:43:18.757 24195 24223 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-05 10:43:18.757 24195 24223 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 24195
09-05 10:43:18.757 24195 24223 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-05 10:43:18.757 24195 24223 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-05 10:43:18.757 24195 24223 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-05 10:43:18.757 24195 24223 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-05 10:43:18.757 24195 24223 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-05 10:43:18.757 24195 24223 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-05 10:43:18.757 24195 24223 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-05 10:43:52.962 24288 24314 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-05 10:43:52.962 24288 24314 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 24288
09-05 10:43:52.962 24288 24314 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-05 10:43:52.962 24288 24314 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-05 10:43:52.962 24288 24314 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-05 10:43:52.962 24288 24314 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-05 10:43:52.962 24288 24314 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-05 10:43:52.962 24288 24314 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-05 10:43:52.962 24288 24314 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-05 10:43:56.227 24390 24416 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-05 10:43:56.227 24390 24416 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 24390
09-05 10:43:56.227 24390 24416 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-05 10:43:56.227 24390 24416 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-05 10:43:56.227 24390 24416 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-05 10:43:56.227 24390 24416 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-05 10:43:56.227 24390 24416 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-05 10:43:56.227 24390 24416 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-05 10:43:56.227 24390 24416 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-05 10:45:00.351 24781 24844 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
09-05 10:45:00.351 24781 24844 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 24781
09-05 10:45:00.351 24781 24844 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-05 10:45:00.351 24781 24844 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-05 10:45:00.351 24781 24844 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-05 10:45:00.351 24781 24844 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-05 10:45:00.351 24781 24844 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-05 10:45:00.351 24781 24844 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-05 10:45:00.351 24781 24844 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-05 10:45:03.799 24856 24882 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-05 10:45:03.799 24856 24882 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 24856
09-05 10:45:03.799 24856 24882 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-05 10:45:03.799 24856 24882 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-05 10:45:03.799 24856 24882 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-05 10:45:03.799 24856 24882 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-05 10:45:03.799 24856 24882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-05 10:45:03.799 24856 24882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-05 10:45:03.799 24856 24882 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-06 11:04:33.471 11878 11904 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-06 11:04:33.471 11878 11904 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 11878
09-06 11:04:33.471 11878 11904 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-06 11:04:33.471 11878 11904 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-06 11:04:33.471 11878 11904 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-06 11:04:33.471 11878 11904 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-06 11:04:33.471 11878 11904 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 11:04:33.471 11878 11904 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 11:04:33.471 11878 11904 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-06 11:04:40.562 11939 11966 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-06 11:04:40.562 11939 11966 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 11939
09-06 11:04:40.562 11939 11966 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-06 11:04:40.562 11939 11966 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-06 11:04:40.562 11939 11966 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-06 11:04:40.562 11939 11966 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-06 11:04:40.562 11939 11966 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 11:04:40.562 11939 11966 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 11:04:40.562 11939 11966 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-06 11:04:43.026 11990 12017 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-06 11:04:43.026 11990 12017 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 11990
09-06 11:04:43.026 11990 12017 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-06 11:04:43.026 11990 12017 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-06 11:04:43.026 11990 12017 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-06 11:04:43.026 11990 12017 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-06 11:04:43.026 11990 12017 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 11:04:43.026 11990 12017 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 11:04:43.026 11990 12017 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-06 11:04:46.674 12040 12066 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-06 11:04:46.674 12040 12066 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 12040
09-06 11:04:46.674 12040 12066 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-06 11:04:46.674 12040 12066 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-06 11:04:46.674 12040 12066 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-06 11:04:46.674 12040 12066 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-06 11:04:46.674 12040 12066 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 11:04:46.674 12040 12066 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 11:04:46.674 12040 12066 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-06 11:05:03.783 12098 12125 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
09-06 11:05:03.783 12098 12125 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 12098
09-06 11:05:03.783 12098 12125 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
09-06 11:05:03.783 12098 12125 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:53)
09-06 11:05:03.783 12098 12125 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher.access$fetchScreenshots(ScreenshotFetcher.kt:12)
09-06 11:05:03.783 12098 12125 E AndroidRuntime: 	at org.mozilla.scryer.filemonitor.ScreenshotFetcher$fetchScreenshots$1.run(ScreenshotFetcher.kt:21)
09-06 11:05:03.783 12098 12125 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 11:05:03.783 12098 12125 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 11:05:03.783 12098 12125 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
--------- beginning of main
09-06 11:08:00.686  3178  3178 D vol.SecVolumeDialog: dismissH reason: 2
09-06 11:08:00.686  3178  3178 D vol.SecVolumeDialog: dismissH : false
09-06 11:08:00.686  3178  3178 D ToggleSlider: onReceive : android.intent.action.CLOSE_SYSTEM_DIALOGS
09-06 11:08:00.686  3178  3178 D Tile.MobileDataTile: action:android.intent.action.CLOSE_SYSTEM_DIALOGS
09-06 11:08:00.687  3178  3178 I StatusBarWindowManager: isExpanded:true, false, false, false, false, false
09-06 11:08:00.687  3178  3178 I StatusBarWindowManager: applyHeight:72
09-06 11:08:00.689  3178  3178 D SwipeDoorsillDetector: reset()com.android.systemui.statusbar.phone.NotificationPanelView.resetViews:944 com.android.systemui.statusbar.phone.PanelBar.collapsePanel:173 com.android.systemui.statusbar.phone.PhoneStatusBar.animateCollapsePanels:4390 com.android.systemui.statusbar.phone.PhoneStatusBar.animateCollapsePanels:4336 
09-06 11:08:00.693  3178  3178 D ToggleSlider: onReceive : android.intent.action.CLOSE_SYSTEM_DIALOGS
09-06 11:08:00.693  3178  3178 D BrightnessMirror: hideMirror cancelled since it's not visible
09-06 11:08:00.693  3178  3178 D ToggleSlider: onReceive : android.intent.action.CLOSE_SYSTEM_DIALOGS
09-06 11:08:00.705  2876  4161 D PackageManager: getComponentMetadataForIconTray : org.mozilla.scryer.MainActivity does not exist in mServices
09-06 11:08:00.705  2876  4161 D PackageManager: getComponentMetadataForIconTray : org.mozilla.scryer.MainActivity does not exist in mProviders
09-06 11:08:00.705  2876  4161 D PackageManager: getComponentMetadataForIconTray : org.mozilla.scryer.MainActivity does not exist in mReceivers
09-06 11:08:00.706  3178  3178 D ApplicationPackageManager: updateItemMetaDataForFixedIconScale: package: org.mozilla.scryer.debug
09-06 11:08:00.706  2876  3626 D PackageManager: getSelectedMetaData : packageName(org.mozilla.scryer.debug) or Metadata strings {[Ljava.lang.String;@8df7de0}
09-06 11:08:00.706  3178  3178 I ApplicationPackageManager: load=org.mozilla.scryer.debug, bg=144-144, dr=144-144, forDefault=true, density=0
09-06 11:08:00.708  3178  3178 I ApplicationPackageManager: scaled rate=201.0, size=144, alpha=12, hold=26
09-06 11:08:00.708  3178  3178 D ApplicationPackageManager: iconScale: getScale(): 201.0 getAlpha(): 12
09-06 11:08:00.710  3178  3178 I ApplicationPackageManager: load=org.mozilla.scryer.debug-crop, bg=120-120, dr=144-144
09-06 11:08:00.712  3178  3178 D ViewRootImpl@32c32f2[RecentsActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
09-06 11:08:00.712  3178  3178 D ViewRootImpl@32c32f2[RecentsActivity]: MSG_WINDOW_FOCUS_CHANGED 1
09-06 11:08:00.712  3178  3178 D ViewRootImpl@32c32f2[RecentsActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -970053632}
09-06 11:08:00.713  3178  3178 V InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@6715b4f nm : com.android.systemui ic=null
09-06 11:08:00.713  3178  3178 I InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
09-06 11:08:00.713  2876 19446 D InputMethodManagerService: windowGainedFocus mCurrentFocusedUserId - 0 and mSecureKeypadEnabled-false
09-06 11:08:00.713  2876 19446 V InputMethodManagerService: windowGainedFocus: reason=WINDOW_FOCUS_GAIN client=android.os.BinderProxy@5fe514a inputContext=null missingMethods= attribute=android.view.inputmethod.EditorInfo@ac30899 nm = com.android.systemui controlFlags=#104 softInputMode=#120 windowFlags=#89910500
09-06 11:08:00.713  2876 19446 V InputMethodManagerService: Unspecified window will hide input
09-06 11:08:00.713  2876 19446 V InputMethodManagerService: hideCurrentInputLocked - !shouldHideSoftInput
09-06 11:08:00.714 13451 13451 D InputTransport: Input channel destroyed: fd=72
09-06 11:08:00.714  2876 19446 D InputTransport: Input channel constructed: fd=376
09-06 11:08:00.714  2876 19446 D InputTransport: Input channel destroyed: fd=376
09-06 11:08:00.714  3178  3178 D InputTransport: Input channel constructed: fd=137
09-06 11:08:00.714  9730  9730 I SKBD    : SamsungKeypad onFinishInput took nanoTime: 59308
09-06 11:08:00.714  9730  9730 I SKBD    : SamsungKeypad [IMI] onStartInput - caller packageName : com.android.systemui
09-06 11:08:00.766  3178  3178 D WallpaperService: updateSurface forceRelayout=false redrawNeeded=false myWidth=1920 myHeight=1920 fixedSize=true x = 0 y = 0 mWidth=1920 mHeight=1920
09-06 11:08:00.766  3178  3178 D ImageWallpaper: onVisibilityChanged: mVisible=false visible=true
09-06 11:08:00.766  3178  3178 D ImageWallpaper: Visibility changed to visible=true
09-06 11:08:00.767  3178  3178 D ImageWallpaper: drawFrame=false rotation=0 mLastRotation=0
09-06 11:08:00.767  3178  3178 D ImageWallpaper: drawFrame:[frame.width()]1920[frame.height()]1920
09-06 11:08:00.767  3178  3178 D ImageWallpaper: surfaceDimensionsChanged=false mLastSurfaceRotation=0 mDisplayWidth=-1 mDisplayHeight=-1
09-06 11:08:00.767  3178  3178 D ImageWallpaper: redrawNeeded = false, mOffsetsChanged = false
09-06 11:08:00.767  3178  3178 D ImageWallpaper: Suppressed drawFrame since redraw is not needed and offsets have not changed.
09-06 11:08:00.769 13451 13451 D ViewRootImpl@87ae37b[MainActivity]: mHardwareRenderer.destroy()#1
09-06 11:08:00.771  2395  2395 I SurfaceFlinger: id=539 createSurf (984x132),1 flag=4, thumbnail anim
09-06 11:08:00.782  3178  9746 D WallpaperService: resized:[frame]Rect(0, 0 - 1920, 1920) [newConfig] is null
09-06 11:08:00.786  3178  3178 D WallpaperService: MSG_WINDOW_RESIZED
09-06 11:08:00.786  3178  3178 D WallpaperService: updateSurface forceRelayout=true redrawNeeded=false myWidth=1920 myHeight=1920 fixedSize=true x = 0 y = 0 mWidth=1920 mHeight=1920
09-06 11:08:00.786  3178  3178 V WallpaperService: Changes: creating=false format=false size=false
09-06 11:08:00.791 13451 13451 D ViewRootImpl@87ae37b[MainActivity]: Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
09-06 11:08:00.796  3178  3178 V WallpaperService: New surface=Surface(name=null)/@0xf2c9d0b, frame=Rect(0, 0 - 1920, 1920),relayoutResult=1, mConfiguration={0 1.0 themeSeq = 0 showBtnBg = -1 ?mcc?mnc ?localeList ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?night ?touch ?keyb/?/? ?nav/?}
09-06 11:08:00.796  3178  3178 V WallpaperService: Wallpaper size has changed : 1920, 1920
09-06 11:08:00.796  3178  3178 D ImageWallpaper: onOffsetsChanged: xOffset=0.0, yOffset=0.0, xOffsetStep=0.0, yOffsetStep=0.0, xPixels=0, yPixels=0
09-06 11:08:00.796  3178  3178 D ImageWallpaper: drawFrame=false rotation=0 mLastRotation=0
09-06 11:08:00.796  3178  3178 D ImageWallpaper: drawFrame:[frame.width()]1920[frame.height()]1920
09-06 11:08:00.796  3178  3178 D ImageWallpaper: surfaceDimensionsChanged=false mLastSurfaceRotation=0 mDisplayWidth=-1 mDisplayHeight=-1
09-06 11:08:00.796  3178  3178 D ImageWallpaper: redrawNeeded = false, mOffsetsChanged = false
09-06 11:08:00.796  3178  3178 D ImageWallpaper: Suppressed drawFrame since redraw is not needed and offsets have not changed.
09-06 11:08:00.815  3178  3178 D ViewRootImpl@32c32f2[RecentsActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
09-06 11:08:00.840  3178  3178 D SwipeDoorsillDetector: reset()com.android.systemui.statusbar.phone.NotificationPanelView.resetViews:944 com.android.systemui.statusbar.phone.PanelBar.collapsePanel:173 com.android.systemui.statusbar.phone.PhoneStatusBar.setWindowState:4822 com.android.systemui.statusbar.CommandQueue$H.handleMessage:713 
09-06 11:08:00.844  2876  2886 I art     : Background partial concurrent mark sweep GC freed 40158(3MB) AllocSpace objects, 4(80KB) LOS objects, 25% free, 46MB/62MB, paused 4.599ms total 257.589ms
```

**Comment by cynthiatang** [comment]
Verified: Fixed

Scryer 1.0(210).nightly
Pixel 2
Android 8.1.0
WebView 68.0.3440.91
