### ISSUE TITLE
Crash (Delete a collection -> Tap View All)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#89]
User have some screenshots

1. Launch Scryer
2. Move some shots to a new collection
3. Delete the new collection
4. Tap View All in Quick access

Video: https://drive.google.com/open?id=1Yz3K0nQKg5A4j1CpISdNsbOopS8S3lxs

Reproduce Rate: 10/10

Pixel2 
Android 8.1.0
Scryer: 1.0(180)debug

--------- beginning of crash
```
09-06 16:06:37.048 28676 28676 E AndroidRuntime: FATAL EXCEPTION: main
09-06 16:06:37.048 28676 28676 E AndroidRuntime: Process: org.mozilla.scryer.debug, PID: 28676
09-06 16:06:37.048 28676 28676 E AndroidRuntime: java.lang.IllegalArgumentException: navigation destination org.mozilla.scryer.debug:id/action_navigate_to_collection is unknown to this NavController
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:671)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:630)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at org.mozilla.scryer.landingpage.HomeFragment$initQuickAccessList$1.onMoreClick(HomeFragment.kt:389)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at org.mozilla.scryer.landingpage.QuickAccessAdapter$createMoreHolder$1.onClick(QuickAccessAdapter.kt:95)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25885)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-06 16:06:37.048 28676 28676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-06 16:06:37.053  1187  4080 W ActivityManager:   Force finishing activity org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity
09-06 16:06:37.063 28676 28676 I Process : Sending signal. PID: 28676 SIG: 9
09-06 16:06:37.064   844   844 E lowmemorykiller: Error writing /proc/28676/oom_score_adj; errno=22
09-06 16:06:37.085  1187  1381 W InputDispatcher: channel 'b067610 org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-06 16:06:37.085  1187  1381 E InputDispatcher: channel 'b067610 org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-06 16:06:37.114  1187  5079 I WindowManager: WIN DEATH: Window{b067610 u0 org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity}
09-06 16:06:37.114  1187  5079 W InputDispatcher: Attempted to unregister already unregistered input channel 'b067610 org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity (server)'
09-06 16:06:37.114   712   712 I Zygote  : Process 28676 exited due to signal (9)
09-06 16:06:37.115  1187  4080 I ActivityManager: Process org.mozilla.scryer.debug (pid 28676) has died: vis  +99TOP 
09-06 16:06:37.115  1187  4080 W ActivityManager: Scheduling restart of crashed service org.mozilla.scryer.debug/org.mozilla.scryer.ScryerService in 1000ms
09-06 16:06:37.116  1187  1211 W libprocessgroup: kill(-28676, 9) failed: No such process
09-06 16:06:37.116  1187  1211 I libprocessgroup: Successfully killed process cgroup uid 10193 pid 28676 in 0ms
09-06 16:06:37.119   614   648 W SurfaceFlinger: Attempting to set client state on removed layer: org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity#0
09-06 16:06:37.119   614   648 W SurfaceFlinger: Attempting to destroy on removed layer: org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity#0
09-06 16:06:37.122   614   648 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{11574 token=Token{46a9947 ActivityRecord{b894c86 u0 org.mozilla.scryer.debug/org.mozilla.scryer.MainActivity t886}}}#0
09-06 16:06:37.129  1187  1216 W ActivityManager: setHasOverlayUi called on unknown pid: 28676
09-06 16:06:37.160   614   614 D SurfaceFlinger: duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
09-06 16:06:37.170  6407  6407 I RunnerModule: Event Bus thread is disabled
09-06 16:06:37.170  6407  6407 I SearchServiceCore: Event Bus thread is disabled; marking main thread as EventBus
09-06 16:06:37.177  6407  6407 W SessionLifecycleManager: Handover failed. Creating new session controller.
09-06 16:06:37.184  1755  1755 I WallpaperService: engine resumed
09-06 16:06:37.187  6407 17668 I RunnerModule: Event Bus thread is disabled
09-06 16:06:37.191   827   894 D CHRE    : @ 87996.594: +: id 10, otherClientPresent 1, mode 3
09-06 16:06:37.192   827   894 D CHRE    : @ 87996.594: [ImuCal] Dynamic sensor configuration: high-performance.
09-06 16:06:37.192   827   894 D CHRE    : @ 87996.594: sensorType 9 allowed 1: mergedMode 3, otherClientPresent 1
09-06 16:06:37.193   827   894 D CHRE    : @ 87996.594: sensorType 12 allowed 1: mergedMode 3, otherClientPresent 1
09-06 16:06:37.194   827   894 D CHRE    : @ 87996.594: sensorType 14 allowed 0: mergedMode 3, otherClientPresent 0
09-06 16:06:37.195  6407  6407 I StreamController: registerScope: nowcards-2825665489624829514
09-06 16:06:37.205  6407  6407 W TemplatedStringEvaluato: Got templated string with no display string
09-06 16:06:37.206  6407  6407 I ClusterController: Found empty cluster, or no children successfully created.
09-06 16:06:37.217  6407 14045 W LocationOracle: No location history returned by ContextManager
09-06 16:06:37.230  6407  6407 I StreamRenderer: maybeRegisterNowCardsScope(nowcards-2825665489624829514, com.google.android.sidekick.shared.remoteapi.CardRenderingContext@fa2c2e9)
09-06 16:06:37.260  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.262  6407  6407 I chatty  : uid=10047 com.google.android.googlequicksearchbox:search identical 2 lines
09-06 16:06:37.262  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.267  2609  4138 I Places  : ?: PlacesBleScanner start() with priority 2
09-06 16:06:37.269  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.270  6407  6407 I chatty  : uid=10047 com.google.android.googlequicksearchbox:search identical 2 lines
09-06 16:06:37.271  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.271  2609  4138 I PlaceInferenceEngine: [anon] Changed inference mode: 1
09-06 16:06:37.273   746   746 V ContextHubHal: sendMessageToHub
09-06 16:06:37.274   827   894 D CHRE    : @ 87996.672: Parsed nanoapp message from host: app ID 0x476f6f676c00100b, endpoint 0x0, msgType 0, payload size 10
09-06 16:06:37.274  2609  4138 I PlaceInferenceEngine: [account#-1795736791] Changed inference mode: 1
09-06 16:06:37.274   827   894 I CHRE    : @ 87996.672: [NanoMinion] received MSG Type 0x70, Version 1, 6 bytes
09-06 16:06:37.274   827   894 I CHRE    : @ 87996.672: [AR_CHRE] request.flush
09-06 16:06:37.274   827   894 I CHRE    : @ 87996.672: [AR_CHRE] send to host, reason=3, sampleSize=2, transitionSize=0
09-06 16:06:37.274   827   894 I CHRE    : @ 87996.672: [NanoMinion] sent MSG Type 0x72, Version 0, 34 bytes, MessageId 59
09-06 16:06:37.274  1187  1435 V ContextHubClientManager: Received NanoAppMessage[type = 1025, length = 42 bytes, broadcast, nanoapp = 0x476f6f676c00100b](data = 0xB1000026 00007200 08CAA3F9 291A0B08 ...)
09-06 16:06:37.274  1187  1435 D ContextHubService: Sending message 1025 version 0 from hubHandle 0, appInstance 0, callBackCount 2
09-06 16:06:37.280  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.281  2609  4138 I Places  : Converted 0 out of 58 WiFi scans
09-06 16:06:37.281  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.281  6407  6407 I chatty  : uid=10047 com.google.android.googlequicksearchbox:search identical 1 line
09-06 16:06:37.282  6407  6407 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
09-06 16:06:37.293  6407  6407 W MonetServiceEventQueue: No updates to flush
09-06 16:06:37.294  2609 29072 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
09-06 16:06:37.313  6407  6407 W ServiceUpdateReceiver: Ignoring update for non-existing controller.
09-06 16:06:37.313  6407  6407 W MonetServiceEventQueue: No updates to flush
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: Failure parsing personalized places proto.
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: bkwg: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at bkvo.a(:com.google.android.gms@12874041@12.8.74 (100400-204998136):137)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at bkvo.b(:com.google.android.gms@12874041@12.8.74 (100400-204998136):19)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at azbx.a(:com.google.android.gms@12874041@12.8.74 (100400-204998136):13)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at qbv.run(:com.google.android.gms@12874041@12.8.74 (100400-204998136):3)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at android.os.Handler.handleCallback(Handler.java:873)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at android.os.Looper.loop(Looper.java:193)
09-06 16:06:37.330  2609  4138 E PlaceInferenceEngine: 	at android.os.HandlerThread.run(HandlerThread.java:65)
09-06 16:06:37.333   746   746 V ContextHubHal: sendMessageToHub
09-06 16:06:37.334   827   894 D CHRE    : @ 87996.734: Parsed nanoapp message from host: app ID 0x476f6f676c00100b, endpoint 0x0, msgType 0, payload size 10
09-06 16:06:37.334  1187  1435 V ContextHubClientManager: Received NanoAppMessage[type = 1025, length = 10 bytes, broadcast, nanoapp = 0x476f6f676c00100b](data = 0xC1000006 00007200 2003)
09-06 16:06:37.334   827   894 I CHRE    : @ 87996.734: [NanoMinion] received MSG Type 0x70, Version 1, 6 bytes
09-06 16:06:37.334   827   894 I CHRE    : @ 87996.734: [AR_CHRE] request.flush
09-06 16:06:37.334   827   894 I CHRE    : @ 87996.734: [AR_CHRE] send to host, reason=3, sampleSize=0, transitionSize=0
09-06 16:06:37.334   827   894 I CHRE    : @ 87996.734: [NanoMinion] sent MSG Type 0x72, Version 0, 2 bytes, MessageId 60
09-06 16:06:37.335  1187  1435 D ContextHubService: Sending message 1025 version 0 from hubHandle 0, appInstance 0, callBackCount 2
09-06 16:06:37.340  2609  4138 I Places  : ?: PlacesBleScanner start() with priority 2
09-06 16:06:37.348  2609  4138 I Places  : ?: PlacesBleScanner start() with priority 2
09-06 16:06:37.348  2609  4138 I PlaceInferenceEngine: [anon] Changed inference mode: 1
09-06 16:06:37.348  2609  4138 I PlaceInferenceEngine: [account#-1795736791] Changed inference mode: 1
09-06 16:06:37.365  2609  4138 I Places  : Converted 0 out of 58 WiFi scans
09-06 16:06:37.376  2609 29072 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
09-06 16:06:37.435  2609 29072 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
09-06 16:06:37.453  2609 28718 W ctxmgr  : [AclManager]No 2 for (accnt=account#-1795736791#, com.google.android.gms(10021):PlacesProducer, vrsn=12874000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2609). Was: 2 for 18, account#-1795736791#
09-06 16:06:37.486  2609 29072 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
09-06 16:06:38.148  1187  1210 I ActivityManager: Start proc 29076:org.mozilla.scryer.debug/u0a193 for service org.mozilla.scryer.debug/org.mozilla.scryer.ScryerService
09-06 16:06:38.164 29076 29076 I la.scryer.debu: Late-enabling -Xcheck:jni
09-06 16:06:38.298 29076 29076 I la.scryer.debu: The ClassLoaderContext is a special shared library.
09-06 16:06:38.300  1187  1187 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
09-06 16:06:38.622 29076 29076 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
09-06 16:06:38.623 29076 29076 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
09-06 16:06:38.623 29076 29076 I FirebaseInitProvider: FirebaseApp initialization successful
09-06 16:06:38.651 29076 29101 I FA      : App measurement is starting up, version: 12780
09-06 16:06:38.652 29076 29101 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
09-06 16:06:38.652 29076 29101 I FA      : To enable faster debug mode event logging run:
09-06 16:06:38.652 29076 29101 I FA      :   adb shell setprop debug.firebase.analytics.app org.mozilla.scryer.debug
09-06 16:06:39.723  1187  1187 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@a629874
09-06 16:06:42.246  6407 14045 I EventLogSendingHelper: Sending log events.
09-06 16:06:42.583  1187  1187 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
09-06 16:06:43.997   699 27793 W DnsTlsSocket: SSL_connect error 5, errno=110
09-06 16:06:43.997   699 27794 W DnsTlsSocket: SSL_connect error 5, errno=110
09-06 16:06:44.139   827   894 I CHRE    : @ 88003.539: [AR_CHRE] IDLE => ON
09-06 16:06:45.171  1187  1187 I chatty  : uid=1000 system_server identical 1 line
09-06 16:06:47.044  1816  1909 I QCNEJ/CndHalConnector: -> SND notifyWifiStatusChanged(RatInfo{type=1, subType=101, state=CONNECTED, v4=IfaceAddrPair{iface=wlan0, addr=10.247.34.224}, v6=IfaceAddrPair{iface=, addr=}, timestamp=2018-09-06 16:06:47.043, isAndroidValidated=true, netHandle=608996085773, slotIdx=0} WifiInfo{freq=FIVE_GHz, state=3, ssid=Mozilla Guest, bssid=70:3a:0e:1f:2e:51, dns=[1.1.1.1, 1.0.0.1, 0.0.0.0, 0.0.0.0, ]})
09-06 16:06:47.246  6407 24619 I EventLogSendingHelper: Sending log events.
09-06 16:06:47.964  1187  1187 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
09-06 16:06:51.966  1187  1218 I PowerManagerService: Going to sleep due to screen timeout (uid 1000)...
09-06 16:06:51.966  1187  1187 W UsageStatsService: Event reported without a package name
09-06 16:06:52.024  1647  1647 I vol.Events: writeEvent dismiss_dialog volume_controller
09-06 16:06:52.448  1187  1218 I DisplayPowerController: Blocking screen off
09-06 16:06:52.449  1187  1218 I DisplayPowerController: Unblocked screen off after 0 ms
09-06 16:06:52.470   754   754 I /vendor/bin/hw/android.hardware.health@2.0-service.wahoo: SRAM data: 2737000
09-06 16:06:52.490  1855  1855 E QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
09-06 16:06:52.490  1855  1855 E QtiImsExtUtils: isCarrierConfigEnabled bundle is null
09-06 16:06:52.537   827   894 I VSC     : @ 88011.938: [VSC] Stopping sensor events for sensor 65537
09-06 16:06:52.544  1187  1216 I DisplayManagerService: Display device changed state: "Built-in Screen", OFF
09-06 16:06:52.545   614   614 D SurfaceFlinger: Set power mode=0, type=0 flinger=0x7d2d655000
09-06 16:06:52.556  1755  1755 I WallpaperService: engine paused
09-06 16:06:52.557  1187  1382 I InputReader: Reconfiguring input devices.  changes=0x00000004
09-06 16:06:52.561   616   616 I SDM     : DisplayBase::SetDisplayState: Set state = 0, display 0
09-06 16:06:52.561   827   894 D CHRE    : @ 88011.961: -: id 10, otherClientPresent 0, mode 3
09-06 16:06:52.561   827   894 D CHRE    : @ 88011.961: [ImuCal] Dynamic sensor configuration: stand-by.
09-06 16:06:52.561   827   894 D CHRE    : @ 88011.961: sensorType 9 allowed 1: mergedMode 1, otherClientPresent 0
09-06 16:06:52.561   827   894 D CHRE    : @ 88011.961: sensorType 12 allowed 1: mergedMode 1, otherClientPresent 0
09-06 16:06:52.562   827   894 D CHRE    : @ 88011.969: sensorType 14 allowed 0: mergedMode 3, otherClientPresent 0
09-06 16:06:52.718  6407  6407 I StreamRenderer: cleanUpRendererScope(nowcards-2825665489624829514)
09-06 16:06:52.763  6407  6407 I PBSessionCacheImpl: Deleted sessionId[702556979332] from persistence.
09-06 16:06:52.764   614   614 D SurfaceFlinger: Finished set power mode=0, type=0
09-06 16:06:52.765  1187  1485 D SurfaceControl: Excessive delay in setPowerMode()
09-06 16:06:52.768  1187  1218 I DreamManagerService: Entering dreamland.
09-06 16:06:52.768  1187  1218 I PowerManagerService: Dozing...
09-06 16:06:52.769  1187  1214 I DreamController: Starting dream: name=ComponentInfo{com.android.systemui/com.android.systemui.doze.DozeService}, isTest=false, canDoze=true, userId=0
09-06 16:06:52.771  1647  1647 V StatusBar: mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{4a36946 V.ED..... .......D 0,0-1080,63} canPanelBeCollapsed(): false
09-06 16:06:52.772  1647  1647 I vol.Events: writeEvent dismiss_dialog volume_controller
09-06 16:06:52.773  6407  6407 W SearchServiceCore: Abort, client detached.
09-06 16:06:52.774  6407  6407 I StreamController: cleanUpControllerScope(nowcards-2825665489624829514)
09-06 16:06:52.803  6407 14045 I WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::i, WorkerId=context, id=a49d}
09-06 16:06:52.803  6407 14045 I WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::k, WorkerId=context, id=dc1d12}
09-06 16:06:52.803  6407 14045 I WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::l, WorkerId=context, id=c800ce3}
09-06 16:06:52.804  6407 14045 I WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::j, WorkerId=context, id=104d6e0}
09-06 16:06:52.804  6407 14045 I WorkController: WorkProxy is not enqueued because WorkController is disposed: WorkProxy{Name=context::n, WorkerId=context, id=9c7ed99}
09-06 16:06:52.804  1647  1647 D StatusBar: disable<e i a s b h r c s > disable2<q i n >
09-06 16:06:52.812  1647  1647 D StatusBar: disable<e i a s b h r c s > disable2<q i n >
09-06 16:06:52.863   746   746 V ContextHubHal: sendMessageToHub
09-06 16:06:52.866  1632  1632 I DeviceStatusMonitor: onReceive() : Action = android.intent.action.SCREEN_OFF
09-06 16:06:52.870  1187  1435 V ContextHubClientManager: Received NanoAppMessage[type = 1025, length = 28 bytes, broadcast, nanoapp = 0x476f6f676c00100b](data = 0xD1000018 00007200 08E9C0FB 291A0B08 ...)
```

**Comment by mlwang32** [comment]
Same crash observed by following the same steps on Advan i5C (Android 5.1), Scryer v1.0(181).debug

Log:
[advan_scryer_crash0906_3.txt](https://github.com/mozilla-tw/Scryer/files/2356225/advan_scryer_crash0906_3.txt)

**Comment by weslyhuang** [comment]
crash = S1, 10/10 rate thus P1.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
ScreenshotGo 1.0(454).nightly
